# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2083)),
                ('lastBuildDate', models.DateTimeField()),
                ('generator', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2083)),
                ('guid', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('pubDate', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riganinja.Channel')),
            ],
        ),
    ]
