# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riganinja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='link',
            field=models.CharField(max_length=2083, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='guid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
